### ISSUE TITLE
Sugestão: usar :#transparent no struct

### ISSUE THREAD

**Issue by pdelfino** [wllsena/lambcalc2#2]
Esse :#transparent deixa bem mais fácil para debuggar o struct. Até recentemente, eu não usava porque eu não conhecia...

Não sei se vc já conhece. Mas, se eu fosse usar seriamente seu projeto, era uma das primeiras coisas que eu alteraria para entender melhor

**Comment by wllsena** [comment]
Utilizando ```#:transparent``` a expressão ```(~compile ((λ (n f x) f (n f x)) (λ (f x) x)))``` printa:

```racket
(~application
 (~lambda
  (list (~argument 'n) (~argument 'f) (~argument 'x))
  (~application
   (~argument 'f)
   (~application (~application (~argument 'n) (~argument 'f)) (~argument 'x))))
 (~lambda (list (~argument 'f) (~argument 'x)) (~argument 'x)))
  ```

Enquanto com a função especificada para ```#:methods gen:custom-write``` (linhas: 31, 42 e 51)  printa:

```racket
((λ (n f x) (f ((n f) x))) (λ (f x) x))
```
